<?php

/**
 * @file
 * Contains mailmerge_emails_form_handler.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mailmerge_emails_form_handler_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mailmerge_emails_form_handler module.
    case 'help.page.mailmerge_emails_form_handler':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Mail merge the selected emails') . '</p>';
      return $output;

    default:
  }
}
