#!/bin/bash
# Simple script to enable or disable xdebug profiling

case $1 in
  aon)
    sudo sed -i 's/xdebug.profiler_enable=0/xdebug.profiler_enable=1/g' /etc/php/7.0/apache2/php.ini
    sudo sed -i 's/xdebug.remote_enable=0/xdebug.remote_enable=1/g' /etc/php/7.0/apache2/php.ini
    sudo sed -i 's/xdebug.remote_autostart=0/xdebug.remote_autostart=1/g' /etc/php/7.0/apache2/php.ini
    sudo sed -i 's/;//g' /etc/php/7.0/apache2/conf.d/20-xdebug.ini 

    sudo sed -i 's/xdebug.profiler_enable=1/xdebug.profiler_enable=0/g' /etc/php/7.0/cli/php.ini
    sudo sed -i 's/xdebug.remote_enable=1/xdebug.remote_enable=0/g' /etc/php/7.0/cli/php.ini
    sudo sed -i 's/xdebug.remote_autostart=1/xdebug.remote_autostart=0/g' /etc/php/7.0/cli/php.ini
    sudo sed -i 's/zend_extension=xdebug.so/;zend_extension=xdebug.so/g' /etc/php/7.0/cli/conf.d/20-xdebug.ini 

    sudo service apache2 restart
  ;;
 con)
    sudo sed -i 's/xdebug.profiler_enable=1/xdebug.profiler_enable=0/g' /etc/php/7.0/apache2/php.ini
    sudo sed -i 's/xdebug.remote_enable=1/xdebug.remote_enable=0/g' /etc/php/7.0/apache2/php.ini
    sudo sed -i 's/xdebug.remote_autostart=1/xdebug.remote_autostart=0/g' /etc/php/7.0/apache2/php.ini
    sudo sed -i 's/zend_extension=xdebug.so/;zend_extension=xdebug.so/g' /etc/php/7.0/apache2/conf.d/20-xdebug.ini


    sudo sed -i 's/xdebug.profiler_enable=0/xdebug.profiler_enable=1/g' /etc/php/7.0/cli/php.ini
    sudo sed -i 's/xdebug.remote_enable=0/xdebug.remote_enable=1/g' /etc/php/7.0/cli/php.ini
    sudo sed -i 's/xdebug.remote_autostart=0/xdebug.remote_autostart=1/g' /etc/php/7.0/cli/php.ini
    sudo sed -i 's/;//g' /etc/php/7.0/cli/conf.d/20-xdebug.ini

    sudo service apache2 restart
  ;;
  off)
    sudo sed -i 's/xdebug.profiler_enable=1/xdebug.profiler_enable=0/g' /etc/php/7.0/apache2/php.ini
    sudo sed -i 's/xdebug.remote_enable=1/xdebug.remote_enable=0/g' /etc/php/7.0/apache2/php.ini
    sudo sed -i 's/xdebug.remote_autostart=1/xdebug.remote_autostart=0/g' /etc/php/7.0/apache2/php.ini
    sudo sed -i 's/zend_extension=xdebug.so/;zend_extension=xdebug.so/g' /etc/php/7.0/apache2/conf.d/20-xdebug.ini 

    sudo sed -i 's/xdebug.profiler_enable=1/xdebug.profiler_enable=0/g' /etc/php/7.0/cli/php.ini
    sudo sed -i 's/xdebug.remote_enable=1/xdebug.remote_enable=0/g' /etc/php/7.0/cli/php.ini
    sudo sed -i 's/xdebug.remote_autostart=1/xdebug.remote_autostart=0/g' /etc/php/7.0/cli/php.ini
    sudo sed -i 's/zend_extension=xdebug.so/;zend_extension=xdebug.so/g' /etc/php/7.0/cli/conf.d/20-xdebug.ini 

    sudo service apache2 restart
  ;;
  *)
    echo "Usage: php_debug aon (apache2 debug on) | con (cli debug on) | off (both off)"
  ;;
esac
